# Generated by Django 2.2.3 on 2019-07-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190704_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='individual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/Users/tingwei758/Documents/personal_portfolio/projects/static/img/'),
        ),
    ]
