# Generated by Django 2.2.3 on 2019-07-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190705_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='individual',
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
