# Generated by Django 2.2.3 on 2019-07-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190705_0443'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_url',
        ),
    ]
