# Generated by Django 2.2.3 on 2019-07-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projecthtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthtml',
            name='project',
            field=models.ForeignKey(default='project_detail.html', on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.Project'),
        ),
    ]
