# Generated by Django 2.2.3 on 2019-07-04 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190704_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 20, 59, 21, 919538, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 20, 59, 21, 919568, tzinfo=utc)),
        ),
    ]
