# Generated by Django 2.2.3 on 2019-07-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190704_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
